# Generated by Django 3.2.5 on 2022-08-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='create_time',
            field=models.CharField(default='2022', max_length=16, null=True, verbose_name='入学年份'),
        ),
    ]
