# Generated by Django 3.2.5 on 2022-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220817_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='grade',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='年级'),
        ),
    ]
