# Generated by Django 3.2.5 on 2022-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_members_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='grade',
            field=models.SmallIntegerField(choices=[(1, '硕士一年级'), (2, '硕士二年级'), (3, '硕士三年级'), (4, '博士一年级'), (5, '博士二年级'), (6, '博士三年级'), (7, '博士四年级'), (8, '其他')], null=True, verbose_name='年级'),
        ),
    ]
