# Generated by Django 3.2.5 on 2022-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_members_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='QQ',
        ),
        migrations.RemoveField(
            model_name='members',
            name='native_place',
        ),
        migrations.AddField(
            model_name='members',
            name='phonenumber',
            field=models.CharField(max_length=16, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='members',
            name='create_time',
            field=models.IntegerField(default=2022, max_length=16, null=True, verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='members',
            name='grade',
            field=models.SmallIntegerField(choices=[(1, '硕士一年级'), (2, '硕士二年级'), (3, '硕士三年级'), (4, '博士一年级'), (5, '博士二年级'), (6, '博士三年级'), (7, '博士四年级'), (8, '毕业生'), (9, '其他')], null=True, verbose_name='年级'),
        ),
    ]
