# Generated by Django 3.2.5 on 2022-08-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20220830_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='journal',
            field=models.CharField(max_length=256, null=True, verbose_name='期刊'),
        ),
    ]
