# Generated by Django 3.2.5 on 2022-08-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_articles_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='birthday',
            field=models.DateTimeField(default='2022-9-1', null=True, verbose_name='发布时间'),
        ),
    ]
