# Generated by Django 3.2.5 on 2022-08-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_articles_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='short_name',
            field=models.CharField(default='CDK12.jpg', max_length=64, null=True, verbose_name='图片名称'),
        ),
    ]
