# Generated by Django 3.2.5 on 2022-09-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_articles_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='grade',
            field=models.SmallIntegerField(choices=[(1, '硕士一年级'), (2, '硕士二年级'), (3, '硕士三年级'), (4, '博士一年级'), (5, '博士二年级'), (6, '博士三年级'), (7, '博士四年级'), (8, '博士五年级'), (9, '毕业生'), (10, '博后'), (11, '其他')], null=True, verbose_name='年级'),
        ),
    ]
