# Generated by Django 3.2.5 on 2022-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_members_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=64, verbose_name='管理员')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
