# Generated by Django 3.2.5 on 2022-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='doi',
            field=models.CharField(max_length=256, null=True, verbose_name='doi'),
        ),
    ]
