# Generated by Django 3.2.5 on 2022-09-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_articles_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.TextField(max_length=1024, null=True, verbose_name='摘要(50个单词以内，仅代表论文)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cat_class',
            field=models.SmallIntegerField(choices=[(1, '论文'), (2, '代表性论文'), (3, '专利'), (4, '奖项'), (5, '其他')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='doi',
            field=models.CharField(max_length=256, null=True, verbose_name='doi(暂时不需要填)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='journal',
            field=models.CharField(default='Nat Commun. 2020 Mar 6;11(1):1251.', max_length=256, null=True, verbose_name='期刊信息'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='short_name',
            field=models.CharField(default='CDK12.jpg', max_length=64, null=True, verbose_name='图片名称(仅代表论文)'),
        ),
    ]
