# Generated by Django 3.2.5 on 2022-09-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20220905_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='doi',
            field=models.CharField(blank=True, default='0', max_length=256, null=True, verbose_name='doi(暂时不需要填)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='journal',
            field=models.CharField(default='Nat Commun. 2020 Mar', max_length=256, null=True, verbose_name='期刊信息'),
        ),
        migrations.AlterField(
            model_name='members',
            name='description',
            field=models.CharField(blank=True, default='货拉拉拉不拉拉布拉多', max_length=256, null=True, verbose_name='个人描述'),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(blank=True, default='caiji88@zju.edu.cn', max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
