# Generated by Django 3.2.5 on 2022-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20220905_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ifr',
            field=models.FloatField(blank=True, max_length=32, null=True, verbose_name='影响因子'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='摘要(50个单词以内，仅代表论文)'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='cat_class',
            field=models.SmallIntegerField(choices=[(1, '论文'), (2, '代表性论文'), (3, '专利'), (4, '奖项'), (5, '其他')], default=1, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='doi',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='doi(暂时不需要填)'),
        ),
    ]
