# Generated by Django 3.2.5 on 2022-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20220907_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='y_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='XX级XX'),
        ),
    ]
